<?xml version="1.0" ?>
<sdf version="1.6" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <world name="marsyard2020">
    <physics type="ode">
      <ode>
        <solver>
          <!-- IMPORTANT for skid steering to properly work -->
          <friction_model>cone_model</friction_model>
        </solver>
      </ode>
    </physics>

    <light name='sun' type='directional'>
      <pose frame=''>0 0 100 0.5 0.5 0</pose>
      <diffuse>1 1 1 1</diffuse>
      <specular>0.1 0.1 0.1 1</specular>
      <direction>0.1 0.1 -0.9</direction>
      <attenuation>
        <range>20</range>
        <constant>0.5</constant>
        <linear>0.01</linear>
        <quadratic>0.001</quadratic>
      </attenuation>
      <!-- <cast_shadows>1</cast_shadows> -->
    </light>

    <scene>
      <ambient>0.6 0.6 0.6 1.0</ambient>
      <sky>
        <clouds>
          <speed>12</speed>
        </clouds>
      </sky>
      <!-- <shadows>true</shadows> -->
      <origin_visual>false</origin_visual>
    </scene>

    <!-- Marsyard -->
    <include>
      <uri>model://mars_yard</uri>
    </include>

    <model name="landmark1">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>5.96 1.759 0.9 0 0</pose>
      <static>true</static>

      <link name="landmark1">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet1_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/1</name>
              </script>
            </material>
          </visual>

          <visual name="sheet1_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/1</name>
              </script>
            </material>
          </visual>

          <visual name="sheet1_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/1</name>
              </script>
            </material>
          </visual>

          <visual name="sheet1_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/1</name>
              </script>
            </material>
          </visual>
      </link>
    </model>

     <model name="landmark2">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>-3.632 6.969 0.81 0 0 0</pose>
      <static>true</static>

      <link name="landmark2">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet2_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/2</name>
              </script>
            </material>
          </visual>

          <visual name="sheet2_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/2</name>
              </script>
            </material>
          </visual>

          <visual name="sheet2_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/2</name>
              </script>
            </material>
          </visual>

          <visual name="sheet2_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/2</name>
              </script>
            </material>
          </visual>
      </link>
    </model>
       <model name="landmark3">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>2.464 5.984 0.65 0 0 0</pose>
      <static>true</static>

      <link name="landmark3">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet3_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/3</name>
              </script>
            </material>
          </visual>

          <visual name="sheet3_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/3</name>
              </script>
            </material>
          </visual>

          <visual name="sheet3_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/3</name>
              </script>
            </material>
          </visual>

          <visual name="sheet3_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/3</name>
              </script>
            </material>
          </visual>
      </link>
    </model>

     <model name="landmark4">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>4.163 12.066 0.7 0 0 0</pose>
      <static>true</static>

      <link name="landmark4">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet4_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/4</name>
              </script>
            </material>
          </visual>

          <visual name="sheet4_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/4</name>
              </script>
            </material>
          </visual>

          <visual name="sheet4_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/4</name>
              </script>
            </material>
          </visual>

          <visual name="sheet4_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/4</name>
              </script>
            </material>
          </visual>
      </link>
    </model>

    <model name="landmark5">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>-1.854 15.088 0.75 0 0</pose>
      <static>true</static>

      <link name="landmark5">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet5_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/5</name>
              </script>
            </material>
          </visual>

          <visual name="sheet5_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/5</name>
              </script>
            </material>
          </visual>

          <visual name="sheet5_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/5</name>
              </script>
            </material>
          </visual>

          <visual name="sheet5_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/5</name>
              </script>
            </material>
          </visual>
      </link>
    </model>

     <model name="landmark6">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>-1.73 22.246 0.4 0 0 0</pose>
      <static>true</static>

      <link name="landmark6">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet6_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/6</name>
              </script>
            </material>
          </visual>

          <visual name="sheet6_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/6</name>
              </script>
            </material>
          </visual>

          <visual name="sheet6_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/6</name>
              </script>
            </material>
          </visual>

          <visual name="sheet6_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/6</name>
              </script>
            </material>
          </visual>
      </link>
    </model>
       <model name="landmark7">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>3.205 22.268 0.8 0 0 0</pose>
      <static>true</static>

      <link name="landmark7">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet7_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/7</name>
              </script>
            </material>
          </visual>

          <visual name="sheet7_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/7</name>
              </script>
            </material>
          </visual>

          <visual name="sheet7_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/7</name>
              </script>
            </material>
          </visual>

          <visual name="sheet7_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/7</name>
              </script>
            </material>
          </visual>
      </link>
    </model>

     <model name="landmark8">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>6.863 26.711 0.8 0 0 0</pose>
      <static>true</static>

      <link name="landmark8">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet8_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/8</name>
              </script>
            </material>
          </visual>

          <visual name="sheet8_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/8</name>
              </script>
            </material>
          </visual>

          <visual name="sheet8_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/8</name>
              </script>
            </material>
          </visual>

          <visual name="sheet8_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/8</name>
              </script>
            </material>
          </visual>
      </link>
    </model>
    <model name="landmark9">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>7.905 21.371 0.95 0 0</pose>
      <static>true</static>

      <link name="landmark9">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet9_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/9</name>
              </script>
            </material>
          </visual>

          <visual name="sheet9_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/9</name>
              </script>
            </material>
          </visual>

          <visual name="sheet9_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/9</name>
              </script>
            </material>
          </visual>

          <visual name="sheet9_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/9</name>
              </script>
            </material>
          </visual>
      </link>
    </model>

     <model name="landmark10">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>3.876 18.289 0.6 0 0</pose>
      <static>true</static>

      <link name="landmark10">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet10_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/10</name>
              </script>
            </material>
          </visual>

          <visual name="sheet10_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/10</name>
              </script>
            </material>
          </visual>

          <visual name="sheet10_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/10</name>
              </script>
            </material>
          </visual>

          <visual name="sheet10_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/10</name>
              </script>
            </material>
          </visual>
      </link>
    </model>
       <model name="landmark11">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>6.598 14.024 1.12 0 0 0</pose>
      <static>true</static>

      <link name="landmark11">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet11_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/11</name>
              </script>
            </material>
          </visual>

          <visual name="sheet11_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/11</name>
              </script>
            </material>
          </visual>

          <visual name="sheet11_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/11</name>
              </script>
            </material>
          </visual>

          <visual name="sheet11_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/11</name>
              </script>
            </material>
          </visual>
      </link>
    </model>

     <model name="landmark12">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>11.656 12.69 0.8 0 0 0</pose>
      <static>true</static>

      <link name="landmark12">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet12_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/12</name>
              </script>
            </material>
          </visual>

          <visual name="sheet12_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/12</name>
              </script>
            </material>
          </visual>

          <visual name="sheet12_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/12</name>
              </script>
            </material>
          </visual>

          <visual name="sheet12_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/12</name>
              </script>
            </material>
          </visual>
      </link>
    </model>
    <model name="landmark13">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>6.086 8.467 1.12 0 0</pose>
      <static>true</static>

      <link name="landmark13">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet13_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/13</name>
              </script>
            </material>
          </visual>

          <visual name="sheet13_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/13</name>
              </script>
            </material>
          </visual>

          <visual name="sheet13_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/13</name>
              </script>
            </material>
          </visual>

          <visual name="sheet13_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/13</name>
              </script>
            </material>
          </visual>
      </link>
    </model>

     <model name="landmark14">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>13.864 6.77 0.85 0 0 0</pose>
      <static>true</static>

      <link name="landmark14">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet14_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/14</name>
              </script>
            </material>
          </visual>

          <visual name="sheet14_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/14</name>
              </script>
            </material>
          </visual>

          <visual name="sheet14_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/14</name>
              </script>
            </material>
          </visual>

          <visual name="sheet14_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/14</name>
              </script>
            </material>
          </visual>
      </link>
    </model>
       <model name="landmark15">
      <!-- <xacro:insert_block name="pose"/> -->
      <pose>13.804 1.249 0.78 0 0 </pose>
      <static>true</static>

      <link name="landmark15">
        <visual name="pole_visual">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 0.2 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>0.4</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 0.31 0 0 0</pose>
          <geometry>
            <box>
              <size>0.25 0.25 0.32</size>
            </box>
          </geometry>
        </collision>

         <visual name="sheet15_1">
             <pose>0 0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/15</name>
              </script>
            </material>
          </visual>

          <visual name="sheet15_2">
             <pose>0 -0.1235 0.31 0 0 0</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/15</name>
              </script>
            </material>
          </visual>

          <visual name="sheet15_3">
             <pose>0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/15</name>
              </script>
            </material>
          </visual>

          <visual name="sheet15_4">
             <pose>-0.1235 0 0.31 0 0 1.57</pose>
            <geometry>
              <box>
                <size>0.21 0.005 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/15</name>
              </script>
            </material>
          </visual>
      </link>
    </model>
    <!-- <xacro:include filename="/home/agrim/dev_ws/install/leo_erc_gazebo_worlds/share/leo_erc_gazebo_worlds/worlds/sdf/landmark.sdf.xacro" /> -->
    <!-- <xacro:include filename="/home/agrim/dev_ws/install/leo_erc_gazebo_worlds/share/leo_erc_gazebo_worlds/worlds/sdf/landmark.sdf.xacro"/>
    <xacro:macro name="landmark_with_offset" params="id x y z yaw">
      <xacro:property name="x_offset" value="-17.003807" />
      <xacro:property name="y_offset" value="7.617856" />
      <xacro:property name="z_offset" value="1.352268" />

      <xacro:landmark id="${id}">
        <pose>${x + x_offset} ${y + y_offset} ${z + z_offset} 0 0 ${yaw}</pose>
      </xacro:landmark>
    </xacro:macro>

    <xacro:landmark_with_offset id="2" x="10.0" y="-10.0" z="-0.46" yaw="0.0" />
    <xacro:landmark_with_offset id="3" x="28.35" y="-0.04" z="-0.09" yaw="-0.50" />
    <xacro:landmark_with_offset id="4" x="21.83" y="-2.80" z="-0.28" yaw="-0.29" />
    <xacro:landmark_with_offset id="5" x="18.71" y="-17.19" z="0.23" yaw="0.53" />
    <xacro:landmark_with_offset id="6" x="26.95" y="-7.44" z="-0.08" yaw="-1.35" />
    <xacro:landmark_with_offset id="7" x="15.97" y="7.57" z="-0.41" yaw="-1.31" />
    <xacro:landmark_with_offset id="8" x="17.87" y="-7.57" z="0.10" yaw="-0.79" />
    <xacro:landmark_with_offset id="9" x="10.0" y="10.0" z="-0.39" yaw="-0.90" />
    <xacro:landmark_with_offset id="10" x="29.26" y="-14.52" z="0.13" yaw="-1.52" />
    <xacro:landmark_with_offset id="11" x="18.41" y="-25.83" z="0.31" yaw="0.08" />
    <xacro:landmark_with_offset id="12" x="23.34" y="-14.11" z="0.63" yaw="-0.10" />
    <xacro:landmark_with_offset id="13" x="8.18" y="-18.63" z="0.44" yaw="-0.40" />
    <xacro:landmark_with_offset id="15" x="2.27" y="-16.84" z="-0.1" yaw="-0.56" /> -->
  </world>
</sdf>
